const rankQuestions = {
    White: [
      'What are the three things we bow to at the beginning of class?',
      'How do we greet Instructors at the door?',
      'How do you answer Instructors in the Class?',
      'What does the name "Ping\'an Quan" mean?',
      'Which of the 8pt. Blocks have you learned?',
      'Which Martial Arts make up our system?',
      'What is the name of the style we teach?',
      'What is #3 of the 5 Points of Horse Stance?',
      'How many steps are in Ping\'an Quan?',
      'What is the order of movement in ½ moon stepping?'
    ],
    Yellow: [
      'The Orange Belt falls under which Shaolin Kempo Kung-Fu training category?',
      'Who is the Head Master of the school?',
      'What part of the foot is used for a Front Kick?',
      'Who was the first master of the Shaolin Temple?',
      'The act of Bowing is…',
      'How should the hands be held when in Bao Quan (Front Position)?',
      'What is a Chinese term used for a teacher of Kung-Fu?',
      'What is Ping\'an Quan really teaching us?',
      'Which is one of the 5 Shaolin Animals?',
      'What are the 4 stages of front, back, or side kick?'
    ],
    Orange: [
       'What does the Chinese writing on our school crest translate to?',
       'Tiger represents which element?',
       'What part of the foot is used for a Side Kick?',
       'The forward & backward action when punching is called:',
       'Which 2 Combinations start with same footwork?',
       'The 3 Character Rules are?',
       'What does the name "Wu Bu Quan" mean?',
       'Inside & Outside Crescent kick hit with…',
       'Why is Training Wu Bu Quan important?',
       'The Striking point of Crane wrist is…'
    ],
    Purple: [
      'What is Sanda (Sanshou)?', 
      'What is Self-Defense?', 
      'What part of the foot is used for a Round Kick?', 
      'What are the 3 kicks I learned in Purple Belt?', 
      'How many of the 8pt Open Hand Blocks have you learned?', 
      'The primary arts used in our grappling are:', 
      'How many Animals are part of the Shaolin Training system?',
      'Bodhidharma (or Tamo) is:', 
      'The Shaolin Temple is located in:', 
      '"Shaolin Jiben Gong Shi-ba Shi" means:'
    ],
    Blue: [
      'Crane represents which element? (Basic Book)',
      'The Xu-Bu (Cat stance) is what kind of position?',
      'What part of the foot is used for a Hook Kick?',
      'When performing the 1/2 Moon turn:',
      'The term "Gong-Fu/Kung-fu" actually refers to activities that require:',
      'Level 1 Self-Defense includes',
      'The hands in "Front Position" represent?',
      'How many Directions of Movement are there?',
      'Which are the 4 Defensive Skills of Kempo?',
      'What are 3 strategies used when engaging an opponent in self-defense?'
    ],
    BlueSt: [
      'Arm-bars lock the opponent at the...',
      'How many steps are in Kata 1? (Not including Salutation)',
      'How many steps are in Kata 2? (Not including Salutation)',
      'Which Combination introduces Cat stance?',
      'In what province of China was the Shaolin Temple built?',
      'What does "Lian Huan Quan" mean?',
      'In Lian Huan Quan, how many changes of movement and steps are there?',
      'What are the 2 Qi-Gong routines in Level 1?',
      'The closest of the 3 fighting ranges is:',
      'The "Open Position" in sparring is when...'
    ],
    Green: [
      'Who was considered the first true teacher of Kempo in Okinawa?',
      'The Chinese word for Leopard means: (Basic Book)',
      'Who created the "Quan-Fa" (Kata) forms?',
      'How many types of Elbows are there in the 12pt. system:',
      'What are the 3 main Chin-Na wrist locks?',
      'What leg takedowns are shown in Green Belt?',
      'Which of these Quan-Fa Combos do you have?',
      'What is the aim of Blue Dragon breathing?',
      'When attacking you become more…',
      'Self-Confidence is the ability to…'
    ],
    GreenSt: [
      'Medium stances are good for:',
      'The 3 Planes of motion are:',
      'What is the primary drawback of Spin Kicks?',
      'When executing a Spin kick, it is a good idea to:',
      'Martial Spirit is important because it will...',
      'Why is good Eye Contact important?',
      'What kind of position is the Dragon Stance?',
      'All self-defense skills should be practiced on:',
      'What are the "Three Centers of Power"?',
      'If your opponent has equal skill, strength and speed, what will be the deciding factor for achieving a successful outcome?'
    ],
    GreenSt2: [
      'Who founded Shorin Ryu Kempo?',
      'What is the original name of "Bai He Zi Quan"?',
      'Who was Kushanku?',
      'Crane Stance is unique because:',
      'The name "Babu Lian Huan Quan" means:',
      'What two arts are the origin of Babu Lian Huan Quan?',
      'Which of these Quan-Fa Combos do you have?',
      'What is the aim of White Crane breathing?',
      'Use both Attack & Counter Attack when',
      'A confident person knows how to…'
    ],
    Brown: [
      'Who was the first Hawwaiian Kempo Master?',
      'What was the path of Kempo from Shaolin?',
      'Which statement is False: "Si Liu Bu" is…?',
      'How many steps of the San-Zhan (10-pt.) blocking system have you learned?',
      'What does "San-Zhan" translate to?',
      'What does the Archer exercise benefit?',
      'What is the definition of "Power" in Kung-Fu?',
      'In Brown Belt Self-defense, I have learned:',
      'What Combinations have you learned so far?',
      'When fighting, the eyes should look …'
    ],
    BrownSt: [
      'Who was the first master to bring Kempo to Eastern United States?',
      'From who did Grandmaster Tim learn Kempo?',
      'What are the 2 types of Harmonies?',
      'The name "Shaolin Gong-Fu Quan" means:',
      'How many Harmonies are there?',
      'What is the 21 Tibetans exercise used for?',
      'When judging sparring distance, experienced fighter will position themselves:',
      'The name "Shaolin Gong-Li Quan" means:',
      'What family of Gong-Fu styles did "Gong-Li Quan" originate form?',
      'One of the greatest secrets of Shaolin is...'
    ],
    BrownSt2: [
      'Are you ready?',
      'Are you sure?',
      'Are you really sure?',
      'Like really sure?',
      'Like for real?',
      'You don\'t wanna turn back?',
      'It\'s not too late to leave',
      'Click yes to leave',
      'Aight too bad for you?',
      'Bye bye?',
    ]
}
export default rankQuestions